Fix some formatting issues

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -16,106 +16,106 @@ workflows:
     - script:
         title: Clean _tmp
         inputs:
-          - content: rm -rf ./_tmp
+        - content: rm -rf ./_tmp
     - change-workdir:
         title: Change workdir to _tmp
         run_if: true
         inputs:
-          - path: ./_tmp
+        - path: ./_tmp
     - script:
         title: Download testing resources
         inputs:
-          - content: |-
-              #!/bin/bash
-              set -ex
-              curl -f $APK_DOWNLOAD_URL > $APK_PATH
-              curl -f $MAPPING_DOWNLOAD_URL > $MAPPING_PATH
-              curl -f $AAB_DOWNLOAD_URL > $AAB_PATH
+        - content: |-
+            #!/bin/bash
+            set -ex
+            curl -f $APK_DOWNLOAD_URL > $APK_PATH
+            curl -f $MAPPING_DOWNLOAD_URL > $MAPPING_PATH
+            curl -f $AAB_DOWNLOAD_URL > $AAB_PATH
     - path::./:
         inputs:
-          - app_path: $APK_PATH
-          - api_token: $API_TOKEN
-          - owner_name: $APPCENTER_APP_OWNER
-          - app_name: $APPCENTER_APP_NAME
-          - debug: "no" # Because of the upload
-          - distribution_group: |-
-              Collaborators
-              Public
-          - all_distribution_groups: "no"
-          - mapping_path: $MAPPING_PATH
-          - distribution_tester: tooling.bot@bitrise.io
-          - release_notes: Bitrise step test
+        - app_path: $APK_PATH
+        - api_token: $API_TOKEN
+        - owner_name: $APPCENTER_APP_OWNER
+        - app_name: $APPCENTER_APP_NAME
+        - debug: "no" # Because of the upload
+        - distribution_group: |-
+            Collaborators
+            Public
+        - all_distribution_groups: "no"
+        - mapping_path: $MAPPING_PATH
+        - distribution_tester: tooling.bot@bitrise.io
+        - release_notes: Bitrise step test
     - script:
         title: Check output envs
         inputs:
-          - content: |-
-              #!/bin/bash
-              set -ex
-              if [ -z $APPCENTER_DEPLOY_INSTALL_URL ]
-              then
-                echo "ERROR: APPCENTER_DEPLOY_INSTALL_URL variable empty"
-                exit 1
-              fi
-              if [ -z $APPCENTER_DEPLOY_DOWNLOAD_URL ];
-              then
-                echo "ERROR: APPCENTER_DEPLOY_DOWNLOAD_URL variable empty"
-                exit 1
-              fi
-              if [ -z $APPCENTER_PUBLIC_INSTALL_PAGE_URL ]
-              then
-                echo "ERROR: APPCENTER_PUBLIC_INSTALL_PAGE_URL variable empty"
-                exit 1
-              fi
-              if [ "$APPCENTER_DEPLOY_STATUS" != "success" ]
-              then
-                echo "ERROR: APPCENTER_DEPLOY_STATUS variable is $APPCENTER_DEPLOY_STATUS"
-                exit 1
-              fi
-              if [ -z $APPCENTER_RELEASE_PAGE_URL ]
-              then
-                echo "ERROR: APPCENTER_RELEASE_PAGE_URL variable empty"
-                exit 1
-              fi
-              envman add --key "APPCENTER_DEPLOY_INSTALL_URL" --value ""
-              envman add --key "APPCENTER_DEPLOY_DOWNLOAD_URL" --value ""
-              envman add --key "APPCENTER_PUBLIC_INSTALL_PAGE_URL" --value ""
-              envman add --key "APPCENTER_DEPLOY_STATUS" --value ""
-              envman add --key "APPCENTER_RELEASE_PAGE_URL" --value ""
+        - content: |-
+            #!/bin/bash
+            set -ex
+            if [ -z $APPCENTER_DEPLOY_INSTALL_URL ]
+            then
+              echo "ERROR: APPCENTER_DEPLOY_INSTALL_URL variable empty"
+              exit 1
+            fi
+            if [ -z $APPCENTER_DEPLOY_DOWNLOAD_URL ];
+            then
+              echo "ERROR: APPCENTER_DEPLOY_DOWNLOAD_URL variable empty"
+              exit 1
+            fi
+            if [ -z $APPCENTER_PUBLIC_INSTALL_PAGE_URL ]
+            then
+              echo "ERROR: APPCENTER_PUBLIC_INSTALL_PAGE_URL variable empty"
+              exit 1
+            fi
+            if [ "$APPCENTER_DEPLOY_STATUS" != "success" ]
+            then
+              echo "ERROR: APPCENTER_DEPLOY_STATUS variable is $APPCENTER_DEPLOY_STATUS"
+              exit 1
+            fi
+            if [ -z $APPCENTER_RELEASE_PAGE_URL ]
+            then
+              echo "ERROR: APPCENTER_RELEASE_PAGE_URL variable empty"
+              exit 1
+            fi
+            envman add --key "APPCENTER_DEPLOY_INSTALL_URL" --value ""
+            envman add --key "APPCENTER_DEPLOY_DOWNLOAD_URL" --value ""
+            envman add --key "APPCENTER_PUBLIC_INSTALL_PAGE_URL" --value ""
+            envman add --key "APPCENTER_DEPLOY_STATUS" --value ""
+            envman add --key "APPCENTER_RELEASE_PAGE_URL" --value ""
     - path::./:
         inputs:
-          - app_path: $AAB_PATH
-          - api_token: $API_TOKEN
-          - owner_name: $APPCENTER_APP_OWNER
-          - app_name: $APPCENTER_APP_NAME
-          - debug: "no" # Because of the upload
-          - release_notes: Bitrise step test
+        - app_path: $AAB_PATH
+        - api_token: $API_TOKEN
+        - owner_name: $APPCENTER_APP_OWNER
+        - app_name: $APPCENTER_APP_NAME
+        - debug: "no" # Because of the upload
+        - release_notes: Bitrise step test
     - script:
         title: Check output envs
         inputs:
-          - content: |-
-              #!/bin/bash
-              set -ex
-              if [ -z $APPCENTER_DEPLOY_INSTALL_URL ]
-              then
-                echo "ERROR: APPCENTER_DEPLOY_INSTALL_URL variable empty"
-                exit 1
-              fi
-              if [ -z $APPCENTER_DEPLOY_DOWNLOAD_URL ];
-              then
-                echo "ERROR: APPCENTER_DEPLOY_DOWNLOAD_URL variable empty"
-                exit 1
-              fi
-              if [ -z $APPCENTER_DEPLOY_RELEASE_ID ];
-              then
-                echo "ERROR: APPCENTER_DEPLOY_RELEASE_ID variable empty"
-                exit 1
-              fi
-              if [ "$APPCENTER_DEPLOY_STATUS" != "success" ]
-              then
-                echo "ERROR: APPCENTER_DEPLOY_STATUS variable is $APPCENTER_DEPLOY_STATUS"
-                exit 1
-              fi
-              envman add --key "APPCENTER_DEPLOY_INSTALL_URL" --value ""
-              envman add --key "APPCENTER_DEPLOY_DOWNLOAD_URL" --value ""
-              envman add --key "APPCENTER_DEPLOY_RELEASE_ID" --value ""
-              envman add --key "APPCENTER_DEPLOY_STATUS" --value ""
+        - content: |-
+            #!/bin/bash
+            set -ex
+            if [ -z $APPCENTER_DEPLOY_INSTALL_URL ]
+            then
+              echo "ERROR: APPCENTER_DEPLOY_INSTALL_URL variable empty"
+              exit 1
+            fi
+            if [ -z $APPCENTER_DEPLOY_DOWNLOAD_URL ];
+            then
+              echo "ERROR: APPCENTER_DEPLOY_DOWNLOAD_URL variable empty"
+              exit 1
+            fi
+            if [ -z $APPCENTER_DEPLOY_RELEASE_ID ];
+            then
+              echo "ERROR: APPCENTER_DEPLOY_RELEASE_ID variable empty"
+              exit 1
+            fi
+            if [ "$APPCENTER_DEPLOY_STATUS" != "success" ]
+            then
+              echo "ERROR: APPCENTER_DEPLOY_STATUS variable is $APPCENTER_DEPLOY_STATUS"
+              exit 1
+            fi
+            envman add --key "APPCENTER_DEPLOY_INSTALL_URL" --value ""
+            envman add --key "APPCENTER_DEPLOY_DOWNLOAD_URL" --value ""
+            envman add --key "APPCENTER_DEPLOY_RELEASE_ID" --value ""
+            envman add --key "APPCENTER_DEPLOY_STATUS" --value ""
